# Now lets create the screts 
echo "root" > username.txt
echo "mypassword123" > password.txt
kubectl create secret generic mysecret --from-file=username.txt  --from-file=password.txt
kubectl get secret
kubectl describe secret mysecret
# vi deploysecret.yaml

apiVersion: v1
kind: Pod
metadata:
  name: myvolsecret                  # Pod name
spec:
  containers:
  - name: c1                         # Container name
    image: centos:7                  # Use a valid CentOS tag
    command: ["/bin/bash", "-c", "while true; do echo Technical-guftgu; sleep 5 ; done"]
    volumeMounts:
    - name: testsecret               # Refers to the volume defined below
      mountPath: "/tmp/mysecrets"    # Secret files mounted here (read-only by default)

  volumes:
  - name: testsecret                 # Volume name referenced above
    secret:
      secretName: mysecret           # Must match the Secret you created

kubectl apply -f deploysecret.yaml
kubectl exec myvolsecret -it -- /bin/bash
cd /tmp
ls
cat password.txt