# Create namespace 
apiVersion: v1
kind: Namespace

metadata:
  name: dev
  labels:
    name: dev
kubectl apply -f namespace.yaml
kubectl get namespaces
kubectl get ns
# vi pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: ubuntu
      command:
        - /bin/bash
        - -c
        - while true; do echo Technical Guftgu; sleep 5; done

  restartPolicy: Never
kubectl config current-context
kubectl config set-context $(kubectl config current-context) --namespace=dev #Set default namespace:
kubectl config view | grep namespace:
kubectl apply -f pod.yml
kubectl get pods
kubectl get pods -n dev
kubectl config set-context $(kubectl config current-context) --namespace=default #To switch back to default